language: cpp

branches:
  only:
    - master

env:
  global:
    - secure: KfxZdvimghyw4Drf+vemecuhckgGWBj2Wnue8C99FqLbxFPAdpXgWTnalBLrbeFUHA9tMnhh7DB+Y9kdurKLzCZuYB7ZSRKFskleC6K7W63c3DV/9nmiq/j4K/sv+G+MWyK9DyW6IfJpXweyHxE+7Xpgu/paBsBxR+WjK6DRvyZ0HA8I1J7k2Dti4Zomnw0Ril+n1SBEQfnJJoeAlincETBwM2yV3/Q0vKWWkcYFcpyT+zTee6jYYyLKNd4dCaOpUUQo21cvWEDrk1oKIvFJ9tEOe7pmfBTOTdo6MuKj5TJOpCU7w0QhnmxZy229/9LxSETE+3MKSoLRP2arhZFuKn+LwraezzdzKJ1V0igX4d3c3EodxhR+1dY1iBADRJ2PR401g6ab4ackGzmPsTAn4ERRRoNgFW6LnQOFyB+nwcqlOUImeiVpwrEF4kHDt1uKJuJ808dMmZeBm43yTI7ieVnn14WRsPadBARGM2SGJxEDB6f6RISzazW8Mt45gd+uJNjvgvmRnWO6LIYe3E+djyfBoh6LUjDBqOXGdTmMfeVXZ02qIJuES0NOWwjpLJPKIwj3qNPhTF0lM9+LzejdkU4caRwOgkyyAbmvQDaTaAWAqRc/WZ+32lxn7Ns1bXQ898NM2OZT4ZqEqKGaMUxw1SslDZeLH/3rRwSR1xMu+JU=

git:
  depth: 1

matrix:
  include:
    # OS X El Capitan 10.11
    - env: OSX=el_capitan
      compiler: clang
      os: osx
      osx_image: xcode7.3
    # OS X Sierra 10.12
    - env: OSX=sierra
      compiler: clang
      os: osx
      osx_image: xcode8.3

install:
  - brew update
  - brew install jq
  - brew tap mesos/llvm https://github.com/mesos/llvm
  - brew install --verbose --build-bottle mesos-llvm

script:
  - brew bottle mesos-llvm

after_success:
  - VERSION="$(brew info --json=v1 mesos-llvm | jq -r '.[0].versions.stable')"
  - FILE="mesos-llvm-${VERSION}.${OSX}.bottle.tar.gz"
  - curl -u "${BINTRAY_CREDENTIAL}" -T "${FILE}" -H X-Bintray-Package:llvm -H X-Bintray-Version:"${VERSION}" "https://api.bintray.com/content/apache/mesos/${FILE}"

notifications:
  email: false
